# Generated by Django 5.2.4 on 2025-11-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagerecord',
            name='language_frequency',
            field=models.CharField(blank=True, choices=[('', '未選択'), ('daily', '日常的に使用'), ('often', 'よく使用'), ('sometimes', 'たまに使用'), ('rarely', 'ほとんど使用しない')], default='', max_length=20, verbose_name='言語使用頻度'),
        ),
    ]
