# Generated by Django 5.2.4 on 2025-11-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0002_alter_languagerecord_language_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographicrecord',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='geographicrecord',
            name='thumbnail_path',
        ),
        migrations.AddField(
            model_name='geographicrecord',
            name='media_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='メディアURL'),
        ),
    ]
