# Generated by Django 5.2.4 on 2025-11-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0003_remove_geographicrecord_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographicrecord',
            name='media_url',
        ),
        migrations.AddField(
            model_name='geographicrecord',
            name='file_path',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='ファイルURL'),
        ),
        migrations.AddField(
            model_name='geographicrecord',
            name='thumbnail_path',
            field=models.URLField(blank=True, max_length=1024, verbose_name='サムネイルURL'),
        ),
        migrations.AlterField(
            model_name='languagerecord',
            name='file_path',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='ファイルURL'),
        ),
    ]
