# Generated by Django 5.2.4 on 2025-11-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0004_remove_geographicrecord_media_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicrecord',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='YouTube URL'),
        ),
    ]
