# Generated by Django 5.2.4 on 2026-02-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0005_geographicrecord_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagerecord',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='YouTube URL'),
        ),
    ]
